extends SceneTree
const Collection = preload("res://scripts/triple_triad/triple_triad_collection.gd")
const Deck = preload("res://scripts/triple_triad/triple_triad_deck_store.gd")
const Storage = preload("res://scripts/triple_triad/triple_triad_config_store.gd")
const Catalog = preload("res://data/triple_triad/card_catalog.tres")
const Policy = preload("res://data/triple_triad/acquisition/default_acquisition_policy.tres")
const Resolver = preload("res://scripts/triple_triad/triple_triad_match_resolution_controller.gd")
const Opponent = preload("res://scripts/triple_triad/triple_triad_opponent_collection.gd")
const Economy = preload("res://scripts/triple_triad/triple_triad_card_economy.gd")
var checks := 0
var failures := PackedStringArray()
func _initialize() -> void:
	var isolated := "CodexDeckDurabilityQA-%s" % Time.get_ticks_usec()
	ProjectSettings.set_setting("application/config/use_custom_user_dir", true)
	ProjectSettings.set_setting("application/config/custom_user_dir_name", isolated)
	if not OS.get_user_data_dir().ends_with(isolated) or DirAccess.make_dir_recursive_absolute(OS.get_user_data_dir()) != OK:
		quit(1)
		return
	call_deferred("run")
func check(ok: bool, label: String) -> void:
	checks += 1
	if not ok:
		failures.append(label)
		push_error(label)
func reload_collection():
	var value = Collection.new()
	value.initialize(Catalog, Policy)
	return value
func write_text(path: String, text: String) -> void:
	var file := FileAccess.open(path, FileAccess.WRITE)
	file.store_string(text)
	file.close()
func run() -> void:
	var owned = reload_collection()
	check(owned.unique_owned_count() == 0, "fresh collection starts empty")
	var cards: Array = Policy.build_starting_collection(Catalog)
	check(cards.size() == 5, "authored practice/starter cards")
	var service_parent := Node.new()
	service_parent.name = "FishingSessionServices"
	root.add_child(service_parent)
	var developer := DeveloperPlaytestService.new()
	developer.name = "DeveloperPlaytestService"
	service_parent.add_child(developer)
	developer.set_enabled(true)
	var borrowed: Array = DeveloperPlaytestService.card_test_deck(Catalog, [], Policy, 1, 30)
	check(borrowed.size() == 5 and owned.unique_owned_count() == 0, "practice does not grant ownership")
	developer.set_enabled(false)
	check(DeveloperPlaytestService.card_test_deck(Catalog, [], Policy, 1, 30).is_empty() and reload_collection().unique_owned_count() == 0, "DEV OFF/restart restores real empty ownership")
	service_parent.free()
	for card in cards:
		owned.acquire_card(card)
	var ids := PackedStringArray()
	for card in cards: ids.append(String(card.card_id))
	var config := ConfigFile.new()
	config.set_value("meta", "profile_count", 7)
	config.set_value("meta", "last_profile", 6)
	config.set_value("decks", "deck_ids_7", ids)
	check(Deck.save_config(config) == OK, "save edited profile seven")
	var loaded := ConfigFile.new()
	check(Deck.load_config(loaded) == OK and loaded.get_value("decks", "deck_ids_7") == ids, "exact saved deck order")
	check(Deck.profile_count(loaded) == 7 and Deck.active_profile(loaded) == 6, "canonical profile seven remains active")
	var api := TripleTriadStateAPI.new()
	api.initialize(Catalog, owned, null, null, null, null, null, Policy, null)
	check(api.get_deck_profiles().size() == 7 and api._active_profile_index() == 6, "snapshot agrees with UI profile range")
	var snapshot: Dictionary = owned.get_quantities_snapshot()
	for cycle in range(12):
		check(owned.save_state() == OK, "repeat save %d" % cycle)
		owned = reload_collection()
		check(owned.get_quantities_snapshot() == snapshot, "repeat exact collection %d" % cycle)
		check(Deck.load_config(loaded) == OK and loaded.get_value("decks", "deck_ids_7") == ids, "repeat exact deck %d" % cycle)
	# Invalid IDs, duplicates, excess references and ownership loss: repair, never auto-fill.
	loaded.set_value("decks", "deck_ids_7", PackedStringArray([ids[0], ids[0], "not_a_card", ids[1], ids[2], ids[3], ids[4]]))
	check(Deck.save_config(loaded) == OK, "write malformed references fixture")
	var report: Dictionary = Deck.audit_profiles(Catalog, owned, 30, 1, Policy)
	check(report.valid and report.repairs == 2 and report.profiles_checked == 1, "all seven profiles audited; invalid/duplicate repaired")
	Deck.load_config(loaded)
	check(loaded.get_value("decks", "deck_ids_7") == ids, "deterministic valid order retained")
	owned.remove_card(cards[0])
	report = Deck.audit_profiles(Catalog, owned, 30, 1, Policy)
	Deck.load_config(loaded)
	check(report.valid and loaded.get_value("decks", "deck_ids_7").size() == 4, "lost card pruned; fewer than five not invented")
	check(reload_collection().get_quantities_snapshot() == owned.get_quantities_snapshot(), "loss reload exact")
	var prior: Dictionary = owned.get_quantities_snapshot()
	DirAccess.make_dir_absolute(Collection.SAVE_PATH + ".tmp")
	check(owned.acquire_card(cards[1]) == owned.get_quantity(cards[1]) and owned.get_quantities_snapshot() == prior, "failed atomic write rolls back live ownership")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(Collection.SAVE_PATH + ".tmp"))
	check(owned.set_quantity_by_id(&"invalid", 8) == 0 and owned.get_quantities_snapshot() == prior, "invalid ownership mutation rejected")
	# Truncation recovers the committed backup; staging is never promoted.
	write_text(Collection.SAVE_PATH, "")
	owned = reload_collection()
	check(owned.get_quantities_snapshot() == prior, "zero-byte primary recovers committed ownership")
	write_text(Collection.SAVE_PATH + ".tmp", "[meta]\nversion=3\n[cards]\ninvalid=900\n")
	check(reload_collection().get_quantities_snapshot() == prior, "interrupted staging cannot override primary")
	write_text(Deck.SAVE_PATH, "")
	check(Deck.load_config(loaded) == OK and loaded.get_value("decks", "deck_ids_7").size() == 4, "truncated deck recovers latest committed backup")
	# Invalid primary without recovery copy must not silently seed or overwrite.
	Storage.delete_save(Collection.SAVE_PATH)
	write_text(Collection.SAVE_PATH, "[broken")
	var broken_bytes := FileAccess.get_file_as_bytes(Collection.SAVE_PATH)
	var blocked = reload_collection()
	check(blocked.save_state() != OK and blocked.acquire_card(cards[0]) == 0, "unrecoverable save blocks ownership commit")
	check(FileAccess.get_file_as_bytes(Collection.SAVE_PATH) == broken_bytes, "corrupt evidence not overwritten")
	Storage.delete_save(Collection.SAVE_PATH)
	write_text(Collection.SAVE_PATH, "[meta]\nversion=99\n[cards]\n%s=2\n" % ids[0])
	blocked = reload_collection()
	check(blocked.save_state() != OK and FileAccess.get_file_as_bytes(Collection.SAVE_PATH).get_string_from_utf8().contains("version=99"), "future schema never downgraded")
	Storage.delete_save(Collection.SAVE_PATH)
	owned = reload_collection()
	for card in cards: owned.acquire_card(card)
	# Actual resolver/journal/economy path: retry and restart each win/loss.
	var opponent = Opponent.new()
	opponent.initialize(Catalog, &"durability_opponent", 1, 10, 50)
	var journal := TripleTriadMatchResolutionJournal.new()
	journal.initialize()
	var resolver = Resolver.new()
	resolver.initialize(Catalog, owned, null, null, null, Economy.new(), null, journal, null, null, Policy)
	for winner in [1, 2]:
		var card = cards[0]
		opponent.set_quantity_by_id(card.card_id, 3, true)
		var before: int = owned.get_quantity(card)
		check(journal.begin_resolution({"opponent_id":"durability_opponent", "winner":winner, "player_card_ids":ids, "opponent_card_ids":ids}), "journal starts result %d" % winner)
		var result: Dictionary = resolver.commit_reward_transfer(card, winner, &"durability_opponent", opponent)
		var expected: int = before + (1 if winner == 1 else -1)
		check(result.success and owned.get_quantity(card) == expected, "result transfers once %d" % winner)
		result = resolver.commit_reward_transfer(card, winner, &"durability_opponent", opponent)
		check(result.success and owned.get_quantity(card) == expected, "repeated result idempotent %d" % winner)
		check(reload_collection().get_quantities_snapshot() == owned.get_quantities_snapshot(), "result reload exact %d" % winner)
		journal.clear()
		check(not resolver.commit_reward_transfer(card, winner, &"durability_opponent", opponent).success and owned.get_quantity(card) == expected, "late callback after result completion cannot transfer again %d" % winner)
	var draw_before: Dictionary = owned.get_quantities_snapshot()
	check(not resolver.commit_reward_transfer(cards[0], 0, &"durability_opponent", opponent).success and owned.get_quantities_snapshot() == draw_before, "draw transfers nothing")
	# Replay a persisted acquisition intent as if killed before collection commit.
	var desired: Dictionary = owned.get_quantities_snapshot()
	desired[StringName(cards[1].card_id)] = 4
	var acquisition_config := ConfigFile.new()
	acquisition_config.set_value("meta", "version", 1)
	acquisition_config.set_value("meta", "card_game_unlocked", true)
	acquisition_config.set_value("claimed", "salvaged_card_case", true)
	acquisition_config.set_value("pending", "quantities", desired)
	check(Storage.commit(acquisition_config, TripleTriadAcquisitionService.SAVE_PATH) == OK, "durable acquisition intent")
	var acquisition := TripleTriadAcquisitionService.new()
	acquisition.initialize(Catalog, owned, null, null)
	check(owned.get_quantities_snapshot() == desired and reload_collection().get_quantities_snapshot() == desired, "interrupted grant recovers exact absolute quantities")
	acquisition.initialize(Catalog, owned, null, null)
	check(owned.get_quantities_snapshot() == desired, "grant recovery never duplicates on second load")
	# Legacy profile indices migrate to IDs without lowering the existing save version.
	Deck.load_config(loaded)
	loaded.set_value("decks", "deck_50", PackedInt32Array([int(cards[1].source_index)]))
	check(Deck.save_config(loaded) == OK, "legacy profile fifty accepted")
	var legacy = Catalog.get_card_by_legacy_source_index(int(cards[1].source_index))
	if legacy != null: owned.acquire_card(legacy)
	report = Deck.audit_profiles(Catalog, owned, 50, 6, Policy)
	Deck.load_config(loaded)
	check(report.valid and Deck.profile_count(loaded) == 50 and loaded.has_section_key("decks", "deck_ids_50") and int(loaded.get_value("meta", "version")) == 2, "legacy conversion shares full profile limit and preserves schema")
	# Repeated primary-only half-transfer recovery forces both sides to journal values.
	var economy = Economy.new()
	var transfer_id: StringName = cards[0].card_id
	check(economy._write_journal(transfer_id, &"durability_opponent", 7, 2, false), "pending half-transfer written")
	owned.set_quantity_by_id(transfer_id, 7, true)
	owned = reload_collection()
	check(economy.recover_pending(Catalog, owned) and owned.get_quantity_by_id(transfer_id) == 7, "half-transfer completes without second increment")
	check(economy.recover_pending(Catalog, owned) and reload_collection().get_quantity_by_id(transfer_id) == 7, "repeated transfer recovery idempotent")
	# Card Maker grant path commits quantity/history together; failed intent cannot consume a grant.
	var tracker = preload("res://scripts/triple_triad/triple_triad_acquisition_tracker.gd").new()
	tracker.initialize(Catalog)
	acquisition.initialize(Catalog, owned, tracker, preload("res://data/triple_triad/acquisition/acquisition_registry.tres"))
	var history_before: Dictionary = tracker.get_card_history(cards[2].card_id)
	var grant_before: int = owned.get_quantity(cards[2])
	var granted: Dictionary = acquisition.grant_card(cards[2].card_id, &"card_maker", &"durability", 1)
	check(granted.success and reload_collection().get_quantity(cards[2]) == grant_before + 1, "Card Maker grant persists once")
	check(int(tracker.get_card_history(cards[2].card_id).get("acquired", 0)) == int(history_before.get("acquired", 0)) + 1, "grant metadata reflects same authoritative acquisition")
	var durable_before: Dictionary = owned.get_quantities_snapshot()
	DirAccess.make_dir_absolute(TripleTriadAcquisitionService.SAVE_PATH + ".tmp")
	granted = acquisition.grant_card(cards[2].card_id, &"card_maker", &"failed-intent", 1)
	check(not granted.success and owned.get_quantities_snapshot() == durable_before and reload_collection().get_quantities_snapshot() == durable_before, "failed acquisition intent neither grants nor persists")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(TripleTriadAcquisitionService.SAVE_PATH + ".tmp"))
	# Match-local arrays are copies, not a mutable persistent deck/collection.
	var live = preload("res://scripts/triple_triad/triple_triad_live_match_controller.gd").new()
	live.set_active_player_deck(cards)
	var match_copy: Array = live.get_active_player_deck()
	match_copy.clear()
	check(live.get_active_player_deck().size() == 5 and reload_collection().get_quantities_snapshot() == durable_before, "match-local edits cannot mutate persistent ownership")
	# An interrupted acquisition also replays history to an absolute count.
	acquisition_config.clear()
	acquisition_config.set_value("meta", "version", 1)
	acquisition_config.set_value("pending", "quantities", durable_before)
	acquisition_config.set_value("pending", "history", {String(cards[2].card_id): {"acquired": 8, "lost": 0, "source":"card_maker", "context":"interrupted"}})
	Storage.commit(acquisition_config, TripleTriadAcquisitionService.SAVE_PATH)
	acquisition.initialize(Catalog, owned, tracker, null)
	var history_reloaded = preload("res://scripts/triple_triad/triple_triad_acquisition_tracker.gd").new()
	history_reloaded.initialize(Catalog)
	check(int(history_reloaded.get_card_history(cards[2].card_id).get("acquired", 0)) == 8, "interrupted acquisition history persists with ownership")
	acquisition.initialize(Catalog, owned, history_reloaded, null)
	check(int(history_reloaded.get_card_history(cards[2].card_id).get("acquired", 0)) == 8, "history replay does not duplicate acquisition")
	check(owned.restore_quantities_snapshot({ids[0]: {"bad": 1}}) == ERR_INVALID_DATA and owned.get_quantities_snapshot() == durable_before, "malformed recovery quantities rejected without live mutation")
	# Separate facades cannot checkpoint a stale collection over newer ownership.
	var stale_owner = reload_collection()
	var current_owner = reload_collection()
	current_owner.acquire_card(cards[4])
	var newest: Dictionary = current_owner.get_quantities_snapshot()
	check(stale_owner.save_state() == ERR_BUSY and reload_collection().get_quantities_snapshot() == newest, "stale checkpoint cannot erase newer cards")
	check(stale_owner.acquire_card(cards[3]) == stale_owner.get_quantity(cards[3]) and reload_collection().get_quantities_snapshot() == newest, "stale direct mutation rolls back without overwriting canonical state")
	var stale_service := TripleTriadAcquisitionService.new()
	stale_service.initialize(Catalog, stale_owner, null, null)
	check(not stale_service.grant_card(cards[3].card_id, &"card_maker", &"stale").success and reload_collection().get_quantities_snapshot() == newest, "stale grant cannot journal obsolete ownership")
	check(not economy.reconcile_quantities(Catalog, cards[3].card_id, &"durability_opponent", 0, 1, stale_owner, false) and not economy.has_pending_transfer(), "stale reconciliation cannot journal obsolete quantities")
	# Canonical new-game reset removes primary, recovery and abandoned staging.
	var harness = preload("res://scripts/triple_triad/triple_triad_campaign_qa_harness.gd").new()
	check(harness.apply_scenario(&"fresh", Catalog).success, "new-game reset reports real delete result")
	check(reload_collection().unique_owned_count() == 0 and not FileAccess.file_exists(Deck.SAVE_PATH), "new game resets canonical collection/deck")
	check(not FileAccess.file_exists(Collection.SAVE_PATH + ".tmp") and not FileAccess.file_exists(Deck.SAVE_PATH + ".bak"), "reset cannot resurrect staging/old deck backup")
	check(Node.get_orphan_node_ids().is_empty(), "no detached fixtures")
	print("Deck Ownership Durability QA: %d/%d passed; failures=%s" % [checks-failures.size(), checks, failures])
	quit(0 if failures.is_empty() else 1)
